api.autodiscovery.id: "16555730"
userprofileprocapi:
  name: "userprofile-proc-api"
  version: "v1"
  http:
    path:
      base: "/v1"
      resource: "/*"
      console: "/console/*"
    port: "8082"

accountsysapi:
  http:
    basepath: "/v1" 
    path: 
      users: "/users"
    host: "localhost"
    port: "8083"
    timeout: "120000"
     